# Generated by Django 5.1.6 on 2025-03-14 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('specialty', models.CharField(choices=[('cardiology', 'Kardiologia'), ('neurology', 'Neurologia'), ('dermatology', 'Dermatologia')], max_length=100)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Doctro',
        ),
    ]
