# Generated by Django 5.1.6 on 2025-03-14 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_doctr_delete_doctro'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Doctr',
            new_name='Doctor',
        ),
    ]
