# Generated by Django 5.1.6 on 2025-03-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_doctor_specialty_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('cardiology', 'Kardiologia'), ('neurology', 'Neurologia'), ('dermatology', 'Dermatologia')], max_length=100),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
