# Generated by Django 5.1.7 on 2025-03-22 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_doctor_lastname_alter_doctor_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='lastname',
            field=models.CharField(default='brak', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctor',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(choices=[('Kardiologia', 'Kardiologia'), ('Neurologia', 'Neurologia'), ('Dermatologia', 'Dermatologia')], max_length=100),
        ),
    ]
