# Generated by Django 5.1.7 on 2025-04-09 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_doctor_lastname_alter_doctor_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
