# Generated by Django 5.1.7 on 2025-04-19 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_specialty_doctor_speciality'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='speciality',
            new_name='sspecialty',
        ),
    ]
