# Generated by Django 5.1.7 on 2025-04-19 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_rename_speciality_doctor_sspecialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='sspecialty',
            new_name='specialty',
        ),
    ]
