# Generated by Django 5.1.7 on 2025-04-19 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_sspecialty_doctor_specialty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='specialty',
            new_name='speciality',
        ),
    ]
